### PR TITLE
Create first example (closes #1)

### LINKED ISSUE #1: Create first example

### PR DESCRIPTION
**Pull request by szareiangm**
This is almost the same code but I have addressed the comments and moved it here.

CC: @Nafid @dmatth

### CODE REVIEW

**Review by BenFradet — COMMENTED** [review]
Could you add license headers as well as a license file? Also I think a small readme indicating what this is about would be great, wdyt?

**Comment by szareiangm** [comment]
@BenFradet  Should the headers and the License be like the main repository?

**Comment by BenFradet** [comment]
yup with just the dates as `2019-2019`

**Comment by szareiangm** [comment]
I ran the integration test. everything works. I think it is mergeable.

**Comment by benjben** [comment]
Thanks @szareiangm . I think that we are missing some specs for an HTTP remote adapter, that everyone could use to create its own remote adapter. Something like this:

The HTTP request sent to an adapter contains the following parameters: `contentType`, `queryString`, `headers` and  `body` (JSON).

One request can contain several events.

The body of the HTTP response is expected to be a JSON with either a string field `error` containing the error message if a problem happened on the remote adapter, or a field `events` which is a list of `Map[String, String]`, each map being placed in the parameters of a raw event in the pipeline.

**Comment by szareiangm** [comment]
Hello @benjben . Thanks for reviewing the PR.

Where should I put the specs? In the Readme file or as comment in the code? 

I also need to adjust the code briefly to match whatever we have after reviews in the main repository. That should take one hour or so. If you answer the other question I will do them together. 

By the way, we already have started using this feature internally in our organization and looks very promising.

**Comment by benjben** [comment]
Hi @szareiangm ,

Just in the README, like a *Specs for a remote adapter* section. Thank you.

Awesome! The new release should come before the end of the week.

**Comment by szareiangm** [comment]
Thanks @benjben!  working on it. Will be ready before around noon EST.

**Comment by szareiangm** [comment]
Done

**Comment by benjben** [comment]
Great, thanks @szareiangm !
Out of curiosity, are you using remote adapter with a high throughput?

**Review by benjben — APPROVED** [review]
LGTM

**Comment by szareiangm** [comment]
Thanks! Not high throughput at the moment. But I can tell it was really helpful for the integration.

**Pull request merged**
